CREATE SEQUENCE BOLINF.XXSV_CARGA_AR_INV_CONVIVA_S
START WITH 10011
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER 
;


grant all on XXSV_CARGA_AR_INV_CONVIVA_S to apps with grant option;
