SET DEFINE OFF;

DROP TABLE BOLINF.XXSV_CARGA_APINVOICES CASCADE CONSTRAINTS
/

CREATE TABLE BOLINF.XXSV_CARGA_APINVOICES
(
  IMPORT_TRANSACTION_ID          NUMBER,
  INVOICE_ID                     NUMBER(15),
  INVOICE_NUM                    VARCHAR2(50 BYTE),
  INVOICE_TYPE_LOOKUP_CODE       VARCHAR2(25 BYTE),
  INVOICE_DATE                   DATE,
  PO_NUMBER                      VARCHAR2(20 BYTE),
  VENDOR_ID                      NUMBER(15),
  VENDOR_NUM                     VARCHAR2(30 BYTE),
  VENDOR_NAME                    VARCHAR2(240 BYTE),
  VENDOR_SITE_ID                 NUMBER(15),
  VENDOR_SITE_CODE               VARCHAR2(15 BYTE),
  INVOICE_AMOUNT                 NUMBER,
  INVOICE_CURRENCY_CODE          VARCHAR2(15 BYTE),
  EXCHANGE_RATE                  NUMBER,
  EXCHANGE_RATE_TYPE             VARCHAR2(30 BYTE),
  EXCHANGE_DATE                  DATE,
  TERMS_ID                       NUMBER(15),
  TERMS_NAME                     VARCHAR2(50 BYTE),
  DESCRIPTION                    VARCHAR2(240 BYTE),
  SOURCE                         VARCHAR2(80 BYTE),
  GROUP_ID                       VARCHAR2(80 BYTE),
  REQUEST_ID                     NUMBER,
  PAYMENT_CROSS_RATE_TYPE        VARCHAR2(30 BYTE),
  PAYMENT_CROSS_RATE_DATE        DATE,
  PAYMENT_CROSS_RATE             NUMBER,
  PAYMENT_CURRENCY_CODE          VARCHAR2(15 BYTE),
  WORKFLOW_FLAG                  VARCHAR2(1 BYTE),
  DOC_CATEGORY_CODE              VARCHAR2(30 BYTE),
  VOUCHER_NUM                    VARCHAR2(50 BYTE),
  PAYMENT_METHOD_LOOKUP_CODE     VARCHAR2(25 BYTE),
  PAY_GROUP_LOOKUP_CODE          VARCHAR2(25 BYTE),
  GOODS_RECEIVED_DATE            DATE,
  INVOICE_RECEIVED_DATE          DATE,
  GL_DATE                        DATE,
  ACCTS_PAY_CODE_COMBINATION_ID  NUMBER(15),
  EXCLUSIVE_PAYMENT_FLAG         VARCHAR2(1 BYTE),
  ORG_ID                         NUMBER(15),
  AMOUNT_APPLICABLE_TO_DISCOUNT  NUMBER,
  PREPAY_NUM                     VARCHAR2(50 BYTE),
  PREPAY_DIST_NUM                NUMBER(15),
  PREPAY_APPLY_AMOUNT            NUMBER,
  PREPAY_GL_DATE                 DATE,
  INVOICE_INCLUDES_PREPAY_FLAG   VARCHAR2(1 BYTE),
  NO_XRATE_BASE_AMOUNT           NUMBER,
  VENDOR_EMAIL_ADDRESS           VARCHAR2(2000 BYTE),
  TERMS_DATE                     DATE,
  REQUESTER_ID                   NUMBER(10),
  SHIP_TO_LOCATION               VARCHAR2(40 BYTE),
  EXTERNAL_DOC_REF               VARCHAR2(240 BYTE),
  STATUS                         VARCHAR2(25 BYTE),
  LAST_UPDATE_DATE               DATE,
  LAST_UPDATED_BY                NUMBER(15),
  CREATION_DATE                  DATE,
  CREATED_BY                     NUMBER(15),
  LINE_NUMBER                    NUMBER(15),
  LINE_TYPE_LOOKUP_CODE          VARCHAR2(25 BYTE),
  LINE_GROUP_NUMBER              NUMBER,
  AMOUNT_LINE                    NUMBER,
  DESCRIPTION_LINE               VARCHAR2(240 BYTE),
  AMOUNT_INCLUDES_TAX_FLAG       VARCHAR2(1 BYTE),
  CALC_TAX_DURING_IMPORT_FLAG    VARCHAR2(1 BYTE),
  PRORATE_ACROSS_FLAG            VARCHAR2(1 BYTE),
  TAX_CODE                       VARCHAR2(15 BYTE),
  INVENTORY_ITEM_ID              NUMBER,
  ITEM_DESCRIPTION               VARCHAR2(240 BYTE),
  QUANTITY_INVOICED              NUMBER,
  SHIP_TO_LOCATION_CODE          VARCHAR2(60 BYTE),
  UNIT_PRICE                     NUMBER,
  DISTRIBUTION_SET_ID            NUMBER(15),
  DISTRIBUTION_SET_NAME          VARCHAR2(50 BYTE),
  DIST_CODE_CONCATENATED         VARCHAR2(250 BYTE),
  DIST_CODE_COMBINATION_ID       NUMBER(15),
  AWT_GROUP_ID                   NUMBER(15),
  AWT_GROUP_NAME                 VARCHAR2(25 BYTE),
  PO_RELEASE_ID                  NUMBER,
  RELEASE_NUM                    NUMBER,
  ACCOUNT_SEGMENT                VARCHAR2(25 BYTE),
  BALANCING_SEGMENT              VARCHAR2(25 BYTE),
  COST_CENTER_SEGMENT            VARCHAR2(25 BYTE),
  PROJECT_ID                     NUMBER(15),
  TASK_ID                        NUMBER(15),
  EXPENDITURE_TYPE               VARCHAR2(30 BYTE),
  EXPENDITURE_ITEM_DATE          DATE,
  EXPENDITURE_ORGANIZATION_ID    NUMBER(15),
  PROJECT_ACCOUNTING_CONTEXT     VARCHAR2(30 BYTE),
  PA_ADDITION_FLAG               VARCHAR2(1 BYTE),
  PA_QUANTITY                    NUMBER(22,5),
  USSGL_TRANSACTION_CODE         VARCHAR2(30 BYTE),
  STAT_AMOUNT                    NUMBER,
  TYPE_1099                      VARCHAR2(10 BYTE),
  INCOME_TAX_REGION              VARCHAR2(10 BYTE),
  ASSETS_TRACKING_FLAG           VARCHAR2(1 BYTE),
  PRICE_CORRECTION_FLAG          VARCHAR2(1 BYTE),
  RECEIPT_NUMBER                 VARCHAR2(30 BYTE),
  RECEIPT_LINE_NUMBER            VARCHAR2(25 BYTE),
  MATCH_OPTION                   VARCHAR2(25 BYTE),
  PACKING_SLIP                   VARCHAR2(25 BYTE),
  RCV_TRANSACTION_ID             NUMBER,
  PA_CC_AR_INVOICE_ID            NUMBER(15),
  PA_CC_AR_INVOICE_LINE_NUM      NUMBER(15),
  REFERENCE_1                    VARCHAR2(30 BYTE),
  REFERENCE_2                    VARCHAR2(30 BYTE),
  PA_CC_PROCESSED_CODE           VARCHAR2(1 BYTE),
  TAX_RECOVERY_RATE              NUMBER,
  TAX_RECOVERY_OVERRIDE_FLAG     VARCHAR2(1 BYTE),
  TAX_RECOVERABLE_FLAG           VARCHAR2(1 BYTE),
  TAX_CODE_OVERRIDE_FLAG         VARCHAR2(1 BYTE),
  TAX_CODE_ID                    NUMBER(15),
  TAX                            VARCHAR2(15 BYTE),
  TAX_RATE_CODE                  VARCHAR2(150 BYTE),
  INCL_IN_TAXABLE_LINE_FLAG      VARCHAR2(1 BYTE),
  CREDIT_CARD_TRX_ID             NUMBER(15),
  AWARD_ID                       NUMBER(15),
  VENDOR_ITEM_NUM                VARCHAR2(25 BYTE),
  TAXABLE_FLAG                   VARCHAR2(1 BYTE),
  PRICE_CORRECT_INV_NUM          VARCHAR2(50 BYTE),
  EXTERNAL_DOC_LINE_REF          VARCHAR2(240 BYTE)
)
TABLESPACE XBOLDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


DROP PUBLIC SYNONYM XXSV_CARGA_APINVOICES
/

CREATE UNIQUE INDEX XXSV_CARGA_APINVOICES_U1 ON XXSV_CARGA_APINVOICES (IMPORT_TRANSACTION_ID)
/

CREATE PUBLIC SYNONYM XXSV_CARGA_APINVOICES FOR BOLINF.XXSV_CARGA_APINVOICES
/


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE ON BOLINF.XXSV_CARGA_APINVOICES TO PUBLIC
/

